import { Loader } from "lucide-react";
// Importing the Loader component from the lucide-react library. This component is a Svg image

import { cva, type VariantProps } from "class-variance-authority";
// Importing cva and VariantProps from the class-variance-authority library.
// cva is a utility to define variants for class names and VariantProps is a TypeScript type helper for the variants.

import { cn } from "@/lib/utils";
// Importing the cn function from a local utils library.
// This function is usually used to conditionally combine class names.

const spinnerVariants = cva("text-muted-foreground animate-spin", {
  // Defining spinnerVariants using cva with base classes "text-muted-foreground animate-spin".
  // These base classes apply muted text color and a spin animation to the spinner.

  variants: {
    size: {
      // Defining size variants with different classes for different sizes.
      default: "h-4 w-4", // Default size is 4x4
      sm: "h-2 w-2", // Small size is 2x2
      lg: "h-6 w-6", // Large size is 6x6
      icon: "h-10 w-10", // Icon size is 10x10
    },
  },
  defaultVariants: {
    size: "default", // Setting the default size variant to "default".
  },
});

interface SpinnerProps extends VariantProps<typeof spinnerVariants> {}
// Defining an interface SpinnerProps that extends VariantProps generated from spinnerVariants.
// This interface ensures that only valid size variants can be passed as props to the Spinner component.

export const Spinner = ({ size }: SpinnerProps) => {
  // Exporting a functional component named Spinner.
  // It takes size as a prop which should match one of the size variants defined in spinnerVariants.

  return <Loader className={cn(spinnerVariants({ size }))} />;
  // Rendering the Loader component.
  // The className prop is generated by calling cn with the result of spinnerVariants({ size }).
  // This applies the appropriate size classes to the Loader component based on the size prop.
};
